///|
/// VueNode trait - types that can be children in Vue
pub trait VueNode {
  fn to_vue_node(Self) -> @core.Any
}

///|
pub impl VueNode for VNode with fn to_vue_node(self) {
  @core.identity(self)
}

///|
pub impl VueNode for String with fn to_vue_node(self) {
  @core.identity(self)
}

///|
pub impl VueNode for Int with fn to_vue_node(self) {
  @core.identity(self)
}

///|
pub impl VueNode for Double with fn to_vue_node(self) {
  @core.identity(self)
}

///|
pub impl VueNode for Bool with fn to_vue_node(self) {
  @core.identity(self)
}

///|
pub impl[T : VueNode] VueNode for Array[T] with fn to_vue_node(self) {
  @core.any(self.map(node => node.to_vue_node()))
}

///|
pub impl[T : VueNode] VueNode for T? with fn to_vue_node(self) {
  match self {
    Some(v) => v.to_vue_node()
    None => @core.null()
  }
}
