name: playwright

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'playwright/**'
      - 'playwright_test/**'
      - '.github/workflows/playwright.yaml'
  pull_request:
    paths:
      - 'playwright/**'
      - 'playwright_test/**'
      - '.github/workflows/playwright.yaml'

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Setup Moon
        uses: chawyehsu/setup-moonup@v1
        with:
          moonbit-version: latest
      - name: moon version
        run: |
          moon version --all
      - name: install module dependencies
        run: |
          moon update
          moon install
      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps
      - name: moon check
        run: moon check --deny-warn
      - name: moon test playwright
        run: |
          moon test --no-parallelize -p mizchi/npm_typed/playwright
        env:
          NODE_OPTIONS: "--experimental-wasm-modules --no-warnings=ExperimentalWarnings"
          PLAYWRIGHT_TEST: "1"
